# Generated by Django 4.0.4 on 2022-05-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('IdPago', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la cita')),
                ('MontoPagar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto que se requiere pagar')),
                ('Pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado por el paciente')),
                ('IdCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.cita', verbose_name='Numero de cita correspondiente')),
            ],
        ),
    ]
