# Generated by Django 4.0.3 on 2022-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_rename_idcita_pagos_nocita'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='fechaEmision',
            field=models.DateTimeField(null=True, verbose_name='Fecha en que se emtio el pago'),
        ),
    ]
