# Generated by Django 4.0.4 on 2022-05-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('IdDoctor', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Doctor')),
                ('NomDoctor', models.CharField(max_length=50, verbose_name='Nombre del doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('NoCita', models.AutoField(primary_key=True, serialize=False, verbose_name='No. de Cita')),
                ('NomPaciente', models.CharField(max_length=15, verbose_name='Nombre del paciente')),
                ('Apeterno', models.CharField(max_length=15, verbose_name='Apellido Paterno')),
                ('Amaterno', models.CharField(max_length=15, verbose_name='Apellido Materno')),
                ('FecNacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('Edad', models.IntegerField(verbose_name='Edad del paciente')),
                ('Sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('FechaConsulta', models.DateTimeField(verbose_name='Fecha de la Consulta')),
                ('TotalConsulta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a pagar por la consulta')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.doctor', verbose_name='Doctor asiganado')),
            ],
        ),
    ]
