# Generated by Django 4.0.3 on 2022-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='FecNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
