# Generated by Django 4.0.3 on 2022-05-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0002_alter_cita_fecnacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='Doctor',
        ),
    ]
