# Generated by Django 4.0.3 on 2022-05-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0003_remove_cita_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='DoctAsig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Citas.doctor', verbose_name='Doctor asiganado'),
        ),
    ]
