# Generated by Django 4.0.3 on 2022-05-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0004_cita_doctasig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='DoctAsig',
        ),
    ]
