# Generated by Django 4.0.3 on 2022-05-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0005_remove_cita_doctasig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='NomDoctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Citas.doctor', verbose_name='Doctor Asignado'),
            preserve_default=False,
        ),
    ]
